/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'cc-canvas': 'var(--bg-canvas)',
        'cc-panel': 'var(--bg-panel)',
        'cc-surface': 'var(--bg-surface)',
        'cc-surface-hover': 'var(--bg-surface-hover)',
        'cc-grid-today': 'var(--bg-grid-today)',
        'cc-grid-header': 'var(--bg-grid-header)',
        'cc-text-primary': 'var(--text-primary)',
        'cc-text-secondary': 'var(--text-secondary)',
        'cc-text-tertiary': 'var(--text-tertiary)',
        'cc-text-disabled': 'var(--text-disabled)',
        'cc-accent': 'var(--accent)',
        'cc-accent-hover': 'var(--accent-hover)',
        'cc-accent-subtle': 'var(--accent-subtle)',
        'cc-success': 'var(--status-success)',
        'cc-warning': 'var(--status-warning)',
        'cc-error': 'var(--status-error)',
        'cc-border-subtle': 'var(--border-subtle)',
        'cc-border-default': 'var(--border-default)',
        'cc-border-strong': 'var(--border-strong)',
        'cc-border-accent': 'var(--border-accent)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'Consolas', 'monospace'],
      },
      fontSize: {
        'h1': ['22px', { lineHeight: '1.3', letterSpacing: '-0.32px', fontWeight: '590' }],
        'h2': ['18px', { lineHeight: '1.3', letterSpacing: '-0.22px', fontWeight: '590' }],
        'h3': ['15px', { lineHeight: '1.4', letterSpacing: '-0.16px', fontWeight: '590' }],
        'body-lg': ['14px', { lineHeight: '1.5', fontWeight: '510' }],
        'body': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-em': ['13px', { lineHeight: '1.5', fontWeight: '510' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'caption-em': ['12px', { lineHeight: '1.4', fontWeight: '510' }],
        'label': ['11px', { lineHeight: '1.3', fontWeight: '510' }],
        'micro': ['10px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      borderRadius: {
        'cc-sm': '4px',
        'cc-md': '6px',
        'cc-lg': '8px',
        'cc-xl': '12px',
        'cc-full': '9999px',
      },
      spacing: {
        'topbar': '44px',
        'sidebar': '240px',
        'detail': '280px',
        'timeline': '52px',
      },
      boxShadow: {
        'surface-light': '0 2px 8px rgba(0,0,0,0.08)',
        'surface-dark': '0 4px 24px rgba(0,0,0,0.4)',
        'drag': '0px 4px 16px rgba(0,0,0,0.3)',
      },
    },
  },
  plugins: [],
};
